### ISSUE TITLE
Website not working properly

### ISSUE THREAD

**Issue by Meiyarasan** [alojzjakob/EspSee#1]
Couldn't register new user after all filled up it loads back to https://www.espsee.com/

**Comment by alojzjakob** [comment]
Hi,

did you try re-sending activation email? sometimes it goes to spam or some other tab...
I can definitely see your account but it is not activated

**Comment by Meiyarasan** [comment]
Activation link was not received but I tried resetting the password and it worked. Thank you...

But there is another issue while woking in ESP32-CAM_MJPEG2SD, 
[14:42:26.448 WARN remoteServerConnect] Timed out connecting to server: www.espsee.com, Err: SSL - Memory allocation failed

**Comment by Meiyarasan** [comment]
Its working now Thank you
