### ISSUE TITLE
No cameras in your dashboard…

### ISSUE THREAD

**Issue by guece1** [alojzjakob/EspSee#2]
Hy
I configured everything like in the descripting but 
No cameras in your dashboard…

esp32 send every 30s 
External Heartbeat sent to: www.espsee.com/heartbeat/?token=*********
but no response 
what i do wrong ?

**Comment by alojzjakob** [comment]
Hi,

did you use a correct token and just masked it here for this post?
If you really used stars for token, that explains why it does not work

**Comment by guece1** [comment]
Thank you for your quick reply. 
yes i masked it for the post
my  email i registered for espsee begins with tuer*****@gmail.com
i get activation email and i can login but i dont see my espcam in the dashboard
ESP32-CAM_MJPEG2SD works everything else

**Comment by alojzjakob** [comment]
can you please send me the screenshots and entire logs privately via email, we can reset your token later when we are done testing?

alojzjakob@gmail.com

all i can see right now is that there are no errors in the log and it looks like your camera is not even pinging the heartbeat endpoint...

**Comment by alojzjakob** [comment]
are you connected to SSID that can provide internet access or did you connect to the camera directly on it's own broadcasted ssid?

**Comment by guece1** [comment]
connected true my ssid
i send you a mail

**Comment by alojzjakob** [comment]
an update on https://github.com/s60sc/ESP32-CAM_MJPEG2SD broken heartbeat, token gets truncated when sent as part of url
